#!/bin/bash

if [[ "$1" == */* ]]
then
    echo `git clone git://github.com/$1.git`
    exit 0
else
    username=`git config user.name`
    echo `git clone git://github.com/$username/$1.git`
    exit 0
fi