#!/bin/bash

if [[ "$1" == */* ]]
then
    if [ "$#" -eq 2 ]; then
        echo `git clone git://github.com/$1.git "$2"` 
    else
        echo `git clone git://github.com/$1.git` 
    fi
    exit 0
else
    username=`git config user.name`
    if [ "$#" -eq 2 ]; then
        echo `git clone git://github.com/$username/$1.git` 
    else
        echo `git clone git://github.com/$username/$1.git "$2"` 
    fi
    exit 0
fi