#!/bin/bash

dir=$1
username=`git config user.name`

echo `mkdir $1`
cd $1
echo `git init`

echo `touch README.md`
echo `touch .gitignore`

echo "# $1" >> README.md

echo `git remote add origin git@github.com:$username/$1.git`

